---

- hosts: all
  become: true
  tasks:

    - name: update servers
      package:
        name:
           - "{{ apache_package }}"
           - "{{ php_package }}"
        state: latest
        update_cache: yes 
