---

- hosts: all
  become: true
  tasks:

    - name: update servers
      apt:
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install acpace2 on all servers
      apt: 
        name: apache2
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"]

    - name: install php for apache
      apt:
        name: libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Ubuntu", "Debian"]
   
