---

- hosts: all
  become: true
  pre_tasks:

    - name: update ubuntu servers
      tags: alwways
      apt:
        update_cache: yes
        upgrade: dist 
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks: 

    - name: install httpd on webservers
      tags: ubuntu,apache,php,web
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: copy files to apache server
      tags: copy,apache,web,php,ubuntu
      copy:
        src: demo.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: dev_servers
  become: true
  tasks: 

    - name: install docker on dev_servers
      tags: dev,tree
      apt:
        name:
          - tree
        state: latest
      when: ansible_distribution == "Ubuntu" 
