---

- hosts: all
  become: true
  pre_tasks:

    - name: update ubuntu servers
      tags: alwways
      apt:
        update_cache: yes
        upgrade: dist 
      when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

    - name: add user underbelle to servers
      tags: always
      user:
        name: underbelle
        groups: root

    - name: add ssh key for underbelle
      tags: always
      authorized_key:
          user: underbelle
          key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICFA76lrdDm4vyEYNezsRmVbXldSw8T4lbd/Hikpf4T7 underbelle key"

    - name: add underlle sudoer file
      tags: always
      copy:
        src: underbelle_sudoer
        dest: /etc/sudoers.d/underbelle
        owner: root
        group: root
        mode: 0440



- hosts: web_servers
  become: true
  tasks: 

    - name: install httpd on webservers
      tags: ubuntu,apache,php,web
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: copy files to apache server
      tags: copy,apache,web,php,ubuntu
      copy:
        src: demo.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

    - name: install and unzip terraform
      tags: web,copy
      package:
        name: unzip
      when: ansible_distribution == "Ubuntu"

    - name: install terraform
      tags: web,copy
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.6.5/terraform_1.6.5_linux_amd64.zip 
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root


- hosts: dev_servers
  become: true
  tasks: 

    - name: install docker on dev_servers
      tags: dev,tree
      apt:
        name:
          - tree
        state: latest
      when: ansible_distribution == "Ubuntu" 
